import requests




api_url = "https://movefile-f5du6vlfqa-lz.a.run.app//prediction"
request = {"queries": [{'SalesID': 1139246, 'SalePrice': 66000.0, 'MachineID': 999089, 'ModelID': 3157, 'datasource': 121, 'auctioneerID': 3.0, 'YearMade': 2004, 'MachineHoursCurrentMeter': 68.0, 'UsageBand': 'Low', 'saledate': '2006-11-16 00:00:00', 'fiModelDesc': '521D', 'fiBaseModel': '521', 'fiSecondaryDesc': 'D', 'fiModelSeries': None, 'fiModelDescriptor': None, 'ProductSize': None, 'fiProductClassDesc': 'Wheel Loader - 110.0 to 120.0 Horsepower', 'state': 'Alabama', 'ProductGroup': 'WL', 'ProductGroupDesc': 'Wheel Loader', 'Drive_System': None, 'Enclosure': 'EROPS w AC', 'Forks': 'None or Unspecified', 'Pad_Type': None, 'Ride_Control': 'None or Unspecified', 'Stick': None, 'Transmission': None, 'Turbocharged': None, 'Blade_Extension': None, 'Blade_Width': None, 'Enclosure_Type': None, 'Engine_Horsepower': None, 'Hydraulics': '2 Valve', 'Pushblock': None, 'Ripper': None, 'Scarifier': None, 'Tip_Control': None, 'Tire_Size': 'None or Unspecified', 'Coupler': 'None or Unspecified', 'Coupler_System': None, 'Grouser_Tracks': None, 'Hydraulics_Flow': None, 'Track_Type': None, 'Undercarriage_Pad_Width': None, 'Stick_Length': None, 'Thumb': None, 'Pattern_Changer': None, 'Grouser_Type': None, 'Backhoe_Mounting': None, 'Blade_Type': None, 'Travel_Controls': None, 'Differential_Type': 'Standard', 'Steering_Controls': 'Conventional'}, {'SalesID': 1139248, 'SalePrice': 57000.0, 'MachineID': 117657, 'ModelID': 77, 'datasource': 121, 'auctioneerID': 3.0, 'YearMade': 1996, 'MachineHoursCurrentMeter': 4640.0, 'UsageBand': 'Low', 'saledate': '2004-03-26 00:00:00', 'fiModelDesc': '950FII', 'fiBaseModel': '950', 'fiSecondaryDesc': 'F', 'fiModelSeries': 'II', 'fiModelDescriptor': None, 'ProductSize': 'Medium', 'fiProductClassDesc': 'Wheel Loader - 150.0 to 175.0 Horsepower', 'state': 'North Carolina', 'ProductGroup': 'WL', 'ProductGroupDesc': 'Wheel Loader', 'Drive_System': None, 'Enclosure': 'EROPS w AC', 'Forks': 'None or Unspecified', 'Pad_Type': None, 'Ride_Control': 'None or Unspecified', 'Stick': None, 'Transmission': None, 'Turbocharged': None, 'Blade_Extension': None, 'Blade_Width': None, 'Enclosure_Type': None, 'Engine_Horsepower': None, 'Hydraulics': '2 Valve', 'Pushblock': None, 'Ripper': None, 'Scarifier': None, 'Tip_Control': None, 'Tire_Size': '23.5', 'Coupler': 'None or Unspecified', 'Coupler_System': None, 'Grouser_Tracks': None, 'Hydraulics_Flow': None, 'Track_Type': None, 'Undercarriage_Pad_Width': None, 'Stick_Length': None, 'Thumb': None, 'Pattern_Changer': None, 'Grouser_Type': None, 'Backhoe_Mounting': None, 'Blade_Type': None, 'Travel_Controls': None, 'Differential_Type': 'Standard', 'Steering_Controls': 'Conventional'}]}


response = requests.post(api_url, json=request)
print(response.json())